### ISSUE TITLE
compute command producing SQLite3 syntax error

### ISSUE THREAD

**Issue by felsocim** [jm-cc/gcvb#16]
Reproduced also using *template_example* from the *gcvb-templates* repository, the `python3 -m gcvb compute` command produces the following error for each test task:

```
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.7/dist-packages/gcvb/__main__.py", line 4, in <module>
    command_line.main()
  File "/usr/local/lib/python3.7/dist-packages/gcvb/command_line.py", line 203, in main
    db.end_test(args.first,args.second)
  File "/usr/local/lib/python3.7/dist-packages/gcvb/db.py", line 87, in with_connection_
    return connect(database,f, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/gcvb/db.py", line 65, in connect
    res = f(c, *args, **kwargs) #supposed to contain execute statements.
  File "/usr/local/lib/python3.7/dist-packages/gcvb/db.py", line 146, in end_test
    WHERE id = ? AND run_id = ?""",[test_id,run])
sqlite3.OperationalError: near "WHERE": syntax error
```

Using **gcvb** commit: 960596698b5d4381969956203c965369194fab65

**Comment by jm-cc** [comment]
thanks for catching that one. Since I mainly use the jobrunner now, I did not notice this bug.
