### ISSUE TITLE
About  --data-root  and --yaml-file

### ISSUE THREAD

**Issue by jeromerobert** [jm-cc/gcvb#18]
`generate` have to handy flags `--data-root`,  `--yaml-file`, which allow to do not have input files in the run folder (input files can for example be kept a git repository). The `dashboard` command does not have such flags.

Yet I'm not sure such flag are to be kept on the command line. Would it be more logical to have them in the `config.yaml` file ?

This is not a critical issue because there is an easy workaround with symbolic links. This allow to:
* Make `dashboard` work
* Do not have to add command line flags to `generate` each time
* Keep input data and run folder separated

**Comment by jm-cc** [comment]
Having yaml-file on the command line allows to have result from multiple separated yaml files stored in the same db and the data-root option was intended because sometime  part of your test data might be "private".
Currently, in the dashboard it is only possible to see the last report (but all the data are there), so this intent is not obvious.

We could have some kind of priorities : CLI > config.yaml > default_values.

Also in the *config.yaml* we could define shortcuts for the 3-uple (data_root, yaml_file, modifier) and invoke *generate* with this shortcut. 

As for the dashboard, the information should be retrieved from the database. It is already the case for yaml-file and the modifier, but data-root is not taken into account. I need to look into this, I don't see why data-root is needed for the dashboard now.
What kind of error do you have when you don't add the symbolic links ? Do you also add a symbolic link for the yaml-file ?

**Comment by jeromerobert** [comment]
```
Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/robert/elfipole/gcvb/env/lib/python3.8/site-packages/dash/dash.py", line 1032, in dispatch
    response.set_data(func(*args, outputs_list=outputs_list))
  File "/home/robert/elfipole/gcvb/env/lib/python3.8/site-packages/dash/dash.py", line 967, in add_context
    output_value = func(*args, **kwargs)  # %% callback invoked %%
  File "/home/robert/gcvb/env/lib/python3.8/site-packages/gcvb/dashboard/apps/run.py", line 70, in display_page
    return gen_page(run_id,gcvb_id)
  File "/home/robert/gcvb/env/lib/python3.8/site-packages/gcvb/dashboard/apps/run.py", line 49, in gen_page
    a = loader.load_base(run_id)
  File "/home/robert/gcvb/env/lib/python3.8/site-packages/gcvb/dashboard/apps/loader.py", line 19, in load_base
    self.loaded[(ya,mod)] = yaml_input.load_yaml(ya,mod)
  File "/home/robert/gcvb/env/lib/python3.8/site-packages/gcvb/yaml_input.py", line 29, in load_yaml
    original=util.open_yaml(yaml_file)
  File "/home/robert/gcvb/env/lib/python3.8/site-packages/gcvb/util.py", line 11, in open_yaml
    with open(filename,'r') as stream:
FileNotFoundError: [Errno 2] No such file or directory: 'test.yaml'
```

```
FileNotFoundError: [Errno 2] No such file or directory: './data/tests/references'
127.0.0.1 - - [19/May/2020 11:23:20] "POST /_dash-update-component HTTP/1.1" 500 -
Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/robert/gcvb/env/lib/python3.8/site-packages/dash/dash.py", line 1032, in dispatch
    response.set_data(func(*args, outputs_list=outputs_list))
  File "/home/robert/gcvb/env/lib/python3.8/site-packages/dash/dash.py", line 967, in add_context
    output_value = func(*args, **kwargs)  # %% callback invoked %%
  File "/home/robert/gcvb/env/lib/python3.8/site-packages/gcvb/dashboard/apps/run.py", line 70, in display_page
    return gen_page(run_id,gcvb_id)
  File "/home/robert/gcvb/env/lib/python3.8/site-packages/gcvb/dashboard/apps/run.py", line 49, in gen_page
    a = loader.load_base(run_id)
  File "/home/robert/gcvb/env/lib/python3.8/site-packages/gcvb/dashboard/apps/loader.py", line 20, in load_base
    refs = yaml_input.get_references(self.loaded[(ya,mod)]["Tests"].values(),self.data_root)
  File "/home/robert/gcvb/env/lib/python3.8/site-packages/gcvb/yaml_input.py", line 111, in get_references
    subfolders = [f.name for f in os.scandir(ref_path) if f.is_dir()]
FileNotFoundError: [Errno 2] No such file or directory: './data/tests/references'
127.0.0.1 - - [19/May/2020 11:23:21] "POST /_dash-update-component HTTP/1.1" 500 -
```

**Comment by jm-cc** [comment]
Is this still an issue ?

**Comment by jeromerobert** [comment]
The first error is gone (i.e `test.yaml` file location is well recorded in the db), but the second error remains.

**Comment by jeromerobert** [comment]
Note that the data folder location should not be recorded in the db because we may want to run the tests on a cluster, backup the db, and browse it later on a laptop.

**Comment by jeromerobert** [comment]
Outdated.
