### ISSUE TITLE
sqlite3.OperationalError: database is locked

### ISSUE THREAD

**Issue by jeromerobert** [jm-cc/gcvb#21]
This is happening when inserting results in the db with the parallel job runner:
```
Traceback (most recent call last):
  File "CalcEpsWrapper", line 28, in <module>
    main()
  File "CalcEpsWrapper", line 24, in main
    gcvb.add_metric(args.valid,float(eps))
  File "lib/python3.8/site-packages/gcvb/user_lib.py", line 11, in add_metric
    db.add_metric(run_id, test_id, name, value)
  File "lib/python3.8/site-packages/gcvb/db.py", line 87, in with_connection_
    return connect(database,f, *args, **kwargs)
  File "lib/python3.8/site-packages/gcvb/db.py", line 65, in connect
    res = f(c, *args, **kwargs) #supposed to contain execute statements.
  File "lib/python3.8/site-packages/gcvb/db.py", line 184, in add_metric
    cursor.execute("INSERT INTO valid(metric,value,test_id) VALUES (?,?,?)",[name,value,test_id])
sqlite3.OperationalError: database is locked
```
May be increasing the timeout in `sqlite3.connect` will be enough.

**Comment by jm-cc** [comment]
Ok, the timeout is now 5s for every db operations. I ran into this problem in a different context (when exclusive access was requested explicitly) so the timeout was high only in that case before.

**Comment by jm-cc** [comment]
Can still happen when a lot of concurrent access are made.

**Comment by jm-cc** [comment]
Should be ok now
